version: 0.1.{build}
environment:
  COVECOV_TOKEN:
    secure: QV71IQgoNpmo7RthgwJFHYSOXDi3Af0TDxy28vTMlhiWBwSilG+oplz3JVrxKd11
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
test_script:
- cmd: .\test.cmd