version: 0.1.0-{build}
configuration: Release
environment:
  COVECOV_TOKEN:
    secure: QV71IQgoNpmo7RthgwJFHYSOXDi3Af0TDxy28vTMlhiWBwSilG+oplz3JVrxKd11
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: >-
    dotnet restore

    set DOTNET_BUILD_VERSION=%APPVEYOR_BUILD_NUMBER%

build:
  publish_nuget: true
  verbosity: minimal
after_build:
- cmd: >-
    dotnet pack src/Postbode/project.json
	 
    dotnet pack src/Postbode.Mailgun/project.json
test_script:
- cmd: .\test.cmd

artifacts:
- path: 'src\Postbode*\**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: dOeHvyCsuzlZvo7QYIm6X7w4PzZ/EPw9p9Stkclhh5vStdoaxznuPRgnyU1xKsCP
  on:
    branch: master