version: 0.1.{build}
environment:
  COVERALLS_REPO_TOKEN:
    secure: rq7lGrSI4Rjv2JVEyvJM9Zdf1y8IBCM37/o+1ru3Gg5V9eIrC3SlT8aNVNYBocZg
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
test_script:
- cmd: >- test.cmd